version: '3.9'

services:
  metamorphic:
    image: openjdk:17
    volumes: 
      - ./build/metarmophic.pdf-1.0.jar:/home/dev/metarmophic.pdf-1.0.jar
    command: "java -jar /home/dev/metarmophic.pdf-1.0.jar"
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 1G

